import{initializeApp,getApps}from'https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js';
import{getAuth,onAuthStateChanged,GoogleAuthProvider,signInWithPopup,signOut}from'https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js';
import{getFirestore,collection,doc,getDoc,getDocs,onSnapshot,query,orderBy,limit,addDoc,setDoc,updateDoc,deleteDoc,serverTimestamp}from'https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js';

const CONFIG={apiKey:'AIzaSyBWic36WVTPG5oWUtSCJ-6MWrKWbO_w9aQ',authDomain:'elma-bd38c.firebaseapp.com',projectId:'elma-bd38c',storageBucket:'elma-bd38c.firebasestorage.app',messagingSenderId:'675060354080',appId:'1:675060354080:web:cef2e0c3145440e2d40045'};
const ADMIN_EMAILS=['admin@elmago.com.tr'];
const app=getApps()[0]||initializeApp(CONFIG),auth=getAuth(app),db=getFirestore(app),$=selector=>document.querySelector(selector);
const state={listings:[],reports:[],chats:[],announcements:[],flags:[],audit:[],settings:{},unsubs:[],user:null};
const viewNames={dashboard:'Genel Bakış',listings:'İlanlar',reports:'Şikâyetler',conversations:'Sohbetler',users:'Kullanıcılar',announcements:'Duyurular',settings:'Uygulama Ayarları',audit:'İşlem Geçmişi'};
const dateOf=value=>value?.toDate?.()||value?.seconds&&new Date(value.seconds*1000)||value?new Date(value):null;
const fmt=value=>{const date=dateOf(value);return date&&!Number.isNaN(date.getTime())?new Intl.DateTimeFormat('tr-TR',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(date):'—'};
const safe=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const short=value=>{const text=String(value||'—');return text.length>16?text.slice(0,8)+'…'+text.slice(-5):text};
const isAdmin=user=>user?.emailVerified===true&&ADMIN_EMAILS.includes(String(user.email||'').toLowerCase());
function toast(message,error=false){const node=$('#adminToast');node.textContent=message;node.className='toast show'+(error?' error':'');clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.className='toast',2600)}
function showLogin(message=''){state.unsubs.splice(0).forEach(stop=>stop());$('#adminApp').hidden=true;$('#adminLogin').hidden=false;$('#adminLoginStatus').textContent=message}
function showApp(user){state.user=user;$('#adminLogin').hidden=true;$('#adminApp').hidden=false;$('#adminIdentity').textContent=user.email||user.uid;subscribeAll()}
async function login(){const button=$('#adminLoginButton');button.disabled=true;try{const result=await signInWithPopup(auth,new GoogleAuthProvider());if(!isAdmin(result.user)){await signOut(auth);showLogin('Bu hesap yönetici olarak yetkilendirilmemiş.')}}catch(error){showLogin(error?.code==='auth/popup-closed-by-user'?'Giriş penceresi kapatıldı.':'Yönetici girişi tamamlanamadı.')}finally{button.disabled=false}}
onAuthStateChanged(auth,user=>{if(!user)return showLogin();if(!isAdmin(user)){signOut(auth);return showLogin('Bu hesap yönetici değil.')}showApp(user)});

function watch(name,source){const stop=onSnapshot(source,snapshot=>{state[name]=snapshot.docs.map(item=>({id:item.id,...item.data()}));renderAll()},error=>toast(name+' verisi alınamadı: '+(error.code||''),true));state.unsubs.push(stop)}
function subscribeAll(){state.unsubs.splice(0).forEach(stop=>stop());watch('listings',query(collection(db,'lostFoundListings'),limit(500)));watch('reports',query(collection(db,'lostFoundReports'),limit(500)));watch('chats',query(collection(db,'lostFoundContacts'),limit(500)));watch('announcements',query(collection(db,'announcements'),limit(200)));watch('flags',query(collection(db,'adminUserFlags'),limit(500)));watch('audit',query(collection(db,'adminAudit'),orderBy('createdAt','desc'),limit(200)));state.unsubs.push(onSnapshot(doc(db,'adminSettings','public'),snap=>{state.settings=snap.exists()?snap.data():{};renderSettings()},()=>{}))}
function statusOf(item){if(item.status==='pending')return'pending';if(item.status==='solved')return'solved';const expires=dateOf(item.expiresAt);return expires&&expires<new Date()?'expired':'active'}
function users(){const map=new Map(),put=(uid,name='',email='')=>{if(!uid)return;const item=map.get(uid)||{uid,name:'',email:'',listings:0,chats:0,reports:0};if(name&&!item.name)item.name=name;if(email&&!item.email)item.email=email;map.set(uid,item)};state.listings.forEach(x=>{put(x.ownerUid,x.ownerName,x.ownerEmail);map.get(x.ownerUid).listings++});state.chats.forEach(x=>{put(x.ownerUid);put(x.requesterUid,x.requesterName);if(x.ownerUid)map.get(x.ownerUid).chats++;if(x.requesterUid)map.get(x.requesterUid).chats++});state.reports.forEach(x=>{put(x.reporterUid);if(x.reporterUid)map.get(x.reporterUid).reports++});return[...map.values()].map(x=>({...x,blocked:Boolean(state.flags.find(f=>f.id===x.uid)?.blocked)}))}
function badge(text,type=''){return'<span class="pill '+type+'">'+safe(text)+'</span>'}
function empty(text){return'<div class="empty">'+safe(text)+'</div>'}
function renderStats(){const active=state.listings.filter(x=>statusOf(x)==='active').length,solved=state.listings.filter(x=>statusOf(x)==='solved').length,pendingListings=state.listings.filter(x=>statusOf(x)==='pending').length,pending=state.reports.filter(x=>!['resolved','dismissed'].includes(x.status)).length,blocked=state.flags.filter(x=>x.blocked).length;$('#statsGrid').innerHTML=[['Onay bekleyen ilan',pendingListings],['Aktif ilan',active],['Bekleyen şikâyet',pending],['Engelli kullanıcı',blocked]].map(([label,count])=>'<article class="stat"><span class="eyebrow">CANLI</span><b>'+count+'</b><small>'+label+'</small></article>').join('');$('#navListings').textContent=state.listings.length;$('#navReports').textContent=pending;$('#navChats').textContent=state.chats.length;$('#navUsers').textContent=users().length;$('#navAnnouncements').textContent=state.announcements.filter(x=>x.published).length}
function renderDashboard(){const recent=[...state.listings].sort((a,b)=>(dateOf(b.createdAt)||0)-(dateOf(a.createdAt)||0)).slice(0,6),reports=[...state.reports].filter(x=>!['resolved','dismissed'].includes(x.status)).slice(0,6);$('#recentListings').innerHTML=recent.length?recent.map(x=>'<div class="compact-item"><div><b>'+safe(x.title||'İsimsiz ilan')+'</b><small>'+safe(x.city||'—')+' · '+fmt(x.createdAt)+'</small></div>'+badge(statusOf(x)==='pending'?'Onay bekliyor':statusOf(x)==='active'?'Aktif':'Kapalı',statusOf(x)==='active'?'green':statusOf(x)==='pending'?'red':'')+'</div>').join(''):empty('Henüz ilan yok.');$('#recentReports').innerHTML=reports.length?reports.map(x=>'<div class="compact-item"><div><b>'+safe(x.reason||'Şikâyet')+'</b><small>'+short(x.listingId)+' · '+fmt(x.createdAt)+'</small></div>'+badge('Bekliyor','red')+'</div>').join(''):empty('Bekleyen şikâyet yok.')}
function table(headers,rows){return rows.length?'<table class="data-table"><thead><tr>'+headers.map(x=>'<th>'+x+'</th>').join('')+'</tr></thead><tbody>'+rows.join('')+'</tbody></table>':empty('Gösterilecek kayıt yok.')}
function renderListings(){const term=$('#listingSearch')?.value.toLocaleLowerCase('tr-TR')||'',filter=$('#listingStatus')?.value||'all',items=[...state.listings].filter(x=>(filter==='all'||statusOf(x)===filter)&&[x.title,x.city,x.district,x.ownerName,x.ownerUid].join(' ').toLocaleLowerCase('tr-TR').includes(term)).sort((a,b)=>(dateOf(b.createdAt)||0)-(dateOf(a.createdAt)||0));$('#listingTable').innerHTML=table(['İlan','Konum','Sahibi','Durum','Tarih','İşlem'],items.map(x=>'<tr><td><b>'+safe(x.title||'İsimsiz')+'</b><small>'+safe(x.kind==='found'?'Bulunan':'Kayıp')+' · '+safe(x.category||'Diğer')+'</small></td><td>'+safe([x.district,x.city].filter(Boolean).join(', ')||'—')+'</td><td>'+safe(x.ownerName||'—')+'<small>'+short(x.ownerUid)+'</small></td><td>'+badge(statusOf(x),statusOf(x)==='active'?'green':'')+'</td><td>'+fmt(x.createdAt)+'</td><td><div class="row-actions"><button data-detail="listing" data-id="'+x.id+'">Detay</button>'+(statusOf(x)==='pending'?'<button data-action="approve-listing" data-id="'+x.id+'">Onayla</button>':'<button data-action="toggle-listing" data-id="'+x.id+'">'+(statusOf(x)==='solved'?'Aktifleştir':'Çözüldü')+'</button>')+'<button class="danger" data-action="delete-listing" data-id="'+x.id+'">Sil</button></div></td></tr>'))}
function renderReports(){const items=[...state.reports].sort((a,b)=>(dateOf(b.createdAt)||0)-(dateOf(a.createdAt)||0));$('#reportTable').innerHTML=table(['Neden','İlan','Bildiren','Durum','Tarih','İşlem'],items.map(x=>'<tr><td><b>'+safe(x.reason||'Belirtilmedi')+'</b><small>'+safe(x.note||'')+'</small></td><td>'+short(x.listingId)+'</td><td>'+short(x.reporterUid)+'</td><td>'+badge(x.status||'pending',x.status==='resolved'?'green':x.status==='dismissed'?'':'red')+'</td><td>'+fmt(x.createdAt)+'</td><td><div class="row-actions"><button data-action="resolve-report" data-id="'+x.id+'">Çözüldü</button><button data-action="dismiss-report" data-id="'+x.id+'">Reddet</button><button class="danger" data-action="delete-report" data-id="'+x.id+'">Sil</button></div></td></tr>'))}
function renderChats(){const items=[...state.chats].sort((a,b)=>(dateOf(b.createdAt)||0)-(dateOf(a.createdAt)||0));$('#chatTable').innerHTML=table(['İlan','İlan sahibi','Talep eden','Durum','Tarih','İşlem'],items.map(x=>'<tr><td><b>'+safe(x.listingTitle||'İlan sohbeti')+'</b><small>'+short(x.listingId)+'</small></td><td>'+short(x.ownerUid)+'</td><td>'+safe(x.requesterName||'—')+'<small>'+short(x.requesterUid)+'</small></td><td>'+badge(x.status||'chat',x.status==='rejected'?'red':'green')+'</td><td>'+fmt(x.createdAt)+'</td><td><div class="row-actions"><button data-action="close-chat" data-id="'+x.id+'">Kapat</button><button class="danger" data-action="delete-chat" data-id="'+x.id+'">Sil</button></div></td></tr>'))}
function renderUsers(){const term=$('#userSearch')?.value.toLocaleLowerCase('tr-TR')||'',items=users().filter(x=>[x.name,x.email,x.uid].join(' ').toLocaleLowerCase('tr-TR').includes(term));$('#userTable').innerHTML=table(['Kullanıcı','UID','İlan','Sohbet','Şikâyet','Durum','İşlem'],items.map(x=>'<tr><td><b>'+safe(x.name||'İsimsiz kullanıcı')+'</b><small>'+safe(x.email||'')+'</small></td><td>'+short(x.uid)+'</td><td>'+x.listings+'</td><td>'+x.chats+'</td><td>'+x.reports+'</td><td>'+badge(x.blocked?'Engelli':'Aktif',x.blocked?'red':'green')+'</td><td><div class="row-actions"><button class="'+(x.blocked?'':'danger')+'" data-action="toggle-user" data-id="'+x.uid+'">'+(x.blocked?'Engeli kaldır':'Engelle')+'</button></div></td></tr>'))}
function renderAnnouncements(){const items=[...state.announcements].sort((a,b)=>(dateOf(b.createdAt)||0)-(dateOf(a.createdAt)||0));$('#announcementList').innerHTML=items.length?items.map(x=>'<article class="announcement"><span class="eyebrow">'+safe(x.level||'info')+' · '+safe(x.city||'TÜM ŞEHİRLER')+'</span><h3>'+safe(x.title)+'</h3><p>'+safe(x.body)+'</p><div class="row-actions">'+badge(x.published?'Yayında':'Taslak',x.published?'green':'')+'<button data-action="toggle-announcement" data-id="'+x.id+'">'+(x.published?'Yayından kaldır':'Yayınla')+'</button><button class="danger" data-action="delete-announcement" data-id="'+x.id+'">Sil</button></div></article>').join(''):empty('Henüz duyuru yok.')}
function renderAudit(){const items=state.audit;$('#auditTable').innerHTML=table(['İşlem','Hedef','Yönetici','Tarih'],items.map(x=>'<tr><td><b>'+safe(x.action||'İşlem')+'</b><small>'+safe(x.note||'')+'</small></td><td>'+safe(x.targetType||'—')+' · '+short(x.targetId)+'</td><td>'+safe(x.adminEmail||'—')+'</td><td>'+fmt(x.createdAt)+'</td></tr>'))}
function renderSettings(){if(!$('#settingsForm'))return;$('#maintenanceMode').checked=Boolean(state.settings.maintenance);$('#globalNotice').value=state.settings.globalNotice||'';$('#nearbyRadius').value=state.settings.nearbyRadiusKm||5;$('#listingDays').value=state.settings.listingDurationDays||30}
function renderAll(){renderStats();renderDashboard();renderListings();renderReports();renderChats();renderUsers();renderAnnouncements();renderAudit();renderSettings()}

function openView(name){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id==='view-'+name));document.querySelectorAll('#adminNav button').forEach(x=>x.classList.toggle('active',x.dataset.view===name));$('#viewTitle').textContent=viewNames[name]||name;$('#adminApp').classList.remove('menu-open')}
async function audit(action,targetType,targetId,note=''){await addDoc(collection(db,'adminAudit'),{action,targetType,targetId,note,adminUid:state.user.uid,adminEmail:state.user.email,createdAt:serverTimestamp()})}
async function act(action,id){try{if(action==='approve-listing'){await updateDoc(doc(db,'lostFoundListings',id),{status:'active',approvedAt:serverTimestamp(),approvedBy:state.user.uid,updatedAt:serverTimestamp()});await audit('İlan onaylandı','listing',id)}else if(action==='toggle-listing'){const item=state.listings.find(x=>x.id===id),next=item?.status==='solved'?'active':'solved';await updateDoc(doc(db,'lostFoundListings',id),{status:next,updatedAt:serverTimestamp()});await audit('İlan durumu değiştirildi','listing',id,next)}else if(action==='delete-listing'){if(!confirm('İlan kalıcı olarak silinsin mi?'))return;await deleteDoc(doc(db,'lostFoundListings',id));await audit('İlan silindi','listing',id)}else if(action==='resolve-report'||action==='dismiss-report'){const next=action==='resolve-report'?'resolved':'dismissed';await updateDoc(doc(db,'lostFoundReports',id),{status:next,resolvedAt:serverTimestamp(),resolvedBy:state.user.uid});await audit('Şikâyet işlendi','report',id,next)}else if(action==='delete-report'){if(!confirm('Şikâyet kaydı silinsin mi?'))return;await deleteDoc(doc(db,'lostFoundReports',id));await audit('Şikâyet silindi','report',id)}else if(action==='close-chat'){await updateDoc(doc(db,'lostFoundContacts',id),{status:'rejected',rejectedAt:serverTimestamp()});await audit('Sohbet kapatıldı','chat',id)}else if(action==='delete-chat'){if(!confirm('Sohbet kaydı silinsin mi? Alt mesajlar Firebase tarafından otomatik silinmez.'))return;await deleteDoc(doc(db,'lostFoundContacts',id));await audit('Sohbet kaydı silindi','chat',id)}else if(action==='toggle-user'){const current=state.flags.find(x=>x.id===id),blocked=!current?.blocked;await setDoc(doc(db,'adminUserFlags',id),{blocked,reason:blocked?'Yönetici tarafından engellendi':'',updatedAt:serverTimestamp(),updatedBy:state.user.uid},{merge:true});await audit(blocked?'Kullanıcı engellendi':'Kullanıcı engeli kaldırıldı','user',id)}else if(action==='toggle-announcement'){const item=state.announcements.find(x=>x.id===id);await updateDoc(doc(db,'announcements',id),{published:!item?.published,updatedAt:serverTimestamp()});await audit('Duyuru durumu değiştirildi','announcement',id)}else if(action==='delete-announcement'){if(!confirm('Duyuru silinsin mi?'))return;await deleteDoc(doc(db,'announcements',id));await audit('Duyuru silindi','announcement',id)}toast('İşlem tamamlandı.')}catch(error){console.error(error);toast('İşlem yapılamadı: '+(error.code||error.message),true)}}
function showListing(id){const x=state.listings.find(item=>item.id===id);if(!x)return;$('#modalContent').innerHTML='<span class="eyebrow">İLAN DETAYI</span><h2>'+safe(x.title||'İsimsiz ilan')+'</h2><p>'+safe(x.description||'Açıklama yok')+'</p><div class="detail-grid"><div><small>Tür</small><b>'+safe(x.kind||'—')+'</b></div><div><small>Kategori</small><b>'+safe(x.category||'—')+'</b></div><div><small>Konum</small><b>'+safe([x.district,x.city].filter(Boolean).join(', ')||'—')+'</b></div><div><small>Sahibi</small><b>'+safe(x.ownerName||short(x.ownerUid))+'</b></div><div><small>Durum</small><b>'+safe(statusOf(x))+'</b></div><div><small>Tarih</small><b>'+fmt(x.createdAt)+'</b></div></div><div class="danger-zone"><b>Belge kimliği</b><p>'+safe(x.id)+'</p></div>';$('#adminModal').hidden=false}
function exportData(){const data={exportedAt:new Date().toISOString(),listings:state.listings,reports:state.reports,chats:state.chats,users:users(),announcements:state.announcements,settings:state.settings,audit:state.audit},blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='elmago-admin-export-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}

$('#adminLoginButton').onclick=login;$('#adminLogout').onclick=()=>signOut(auth);$('#adminMenu').onclick=()=>$('#adminApp').classList.toggle('menu-open');$('#refreshAdmin').onclick=subscribeAll;$('#exportAdmin').onclick=exportData;$('#modalClose').onclick=()=>$('#adminModal').hidden=true;$('#adminModal').onclick=event=>{if(event.target.id==='adminModal')event.currentTarget.hidden=true};$('#listingSearch').oninput=renderListings;$('#listingStatus').onchange=renderListings;$('#userSearch').oninput=renderUsers;
$('#adminNav').onclick=event=>{const button=event.target.closest('[data-view]');if(button)openView(button.dataset.view)};document.body.addEventListener('click',event=>{const go=event.target.closest('[data-go]');if(go)openView(go.dataset.go);const detail=event.target.closest('[data-detail="listing"]');if(detail)showListing(detail.dataset.id);const action=event.target.closest('[data-action]');if(action)act(action.dataset.action,action.dataset.id)});
$('#announcementForm').onsubmit=async event=>{event.preventDefault();try{const ref=await addDoc(collection(db,'announcements'),{title:$('#announcementTitle').value.trim(),body:$('#announcementBody').value.trim(),city:$('#announcementCity').value.trim()||'Tümü',level:$('#announcementLevel').value,published:$('#announcementPublished').checked,createdAt:serverTimestamp(),createdBy:state.user.uid});await audit('Duyuru oluşturuldu','announcement',ref.id);event.target.reset();$('#announcementPublished').checked=true;toast('Duyuru kaydedildi.')}catch(error){toast('Duyuru kaydedilemedi: '+(error.code||''),true)}};
$('#settingsForm').onsubmit=async event=>{event.preventDefault();try{await setDoc(doc(db,'adminSettings','public'),{maintenance:$('#maintenanceMode').checked,globalNotice:$('#globalNotice').value.trim(),nearbyRadiusKm:Number($('#nearbyRadius').value)||5,listingDurationDays:Number($('#listingDays').value)||30,updatedAt:serverTimestamp(),updatedBy:state.user.uid},{merge:true});await audit('Uygulama ayarları güncellendi','settings','public');toast('Ayarlar kaydedildi.')}catch(error){toast('Ayarlar kaydedilemedi: '+(error.code||''),true)}};
