(async()=>{
const CONFIG={apiKey:'AIzaSyBWic36WVTPG5oWUtSCJ-6MWrKWbO_w9aQ',authDomain:'elma-bd38c.firebaseapp.com',projectId:'elma-bd38c',storageBucket:'elma-bd38c.firebasestorage.app',messagingSenderId:'675060354080',appId:'1:675060354080:web:cef2e0c3145440e2d40045'};
const [{initializeApp,getApps},{getFirestore,collection,doc,onSnapshot,query,where,limit}]=await Promise.all([import('https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js'),import('https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js')]);
const app=getApps()[0]||initializeApp(CONFIG),db=getFirestore(app);let announcements=[];
const style=document.createElement('style');style.textContent='.eg-admin-notice{position:fixed;z-index:1200;left:50%;top:calc(9px + env(safe-area-inset-top));transform:translateX(-50%);width:min(480px,calc(100% - 24px));border:1px solid #33343a;border-radius:16px;background:#15161a;color:#fff;padding:12px 40px 12px 14px;box-shadow:0 12px 35px #0004;font:750 11px/1.4 Inter,sans-serif}.eg-admin-notice.maintenance{background:#9d2424;border-color:#b73a3a}.eg-admin-notice button{position:absolute;right:8px;top:7px;width:28px;height:28px;border:0;border-radius:50%;background:#ffffff1c;color:#fff}.eg-announcement-layer{position:fixed;z-index:1400;inset:0;display:none;align-items:flex-end;justify-content:center;padding:9px;background:#0009;backdrop-filter:blur(10px)}.eg-announcement-layer.show{display:flex}.eg-announcement-sheet{width:100%;max-width:500px;max-height:88dvh;overflow:auto;border-radius:28px;background:#fff;padding:20px;color:#111}.eg-announcement-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:15px}.eg-announcement-head h2{margin:0;font-size:25px}.eg-announcement-head button{width:38px;height:38px;border:0;border-radius:50%;background:#eeeef0;font-size:21px}.eg-public-announcement{border:1px solid #e0e1e4;border-radius:18px;background:#f7f7f8;padding:15px;margin-top:9px}.eg-public-announcement.urgent{border-color:#e7b6b6;background:#fff2f2}.eg-public-announcement small{color:#777a80;font-size:8px;font-weight:900;letter-spacing:.5px}.eg-public-announcement h3{margin:7px 0;font-size:16px}.eg-public-announcement p{margin:0;color:#55585e;font-size:11px;line-height:1.5}.eg-announcement-empty{padding:35px;text-align:center;color:#777a80}';document.head.appendChild(style);
function notice(data){let node=document.getElementById('egAdminNotice');if(!data?.maintenance&&!data?.globalNotice){node?.remove();return}if(!node){node=document.createElement('div');node.id='egAdminNotice';node.className='eg-admin-notice';node.innerHTML='<span></span><button type="button" aria-label="Kapat">×</button>';node.querySelector('button').onclick=()=>node.remove();document.body.appendChild(node)}node.classList.toggle('maintenance',Boolean(data.maintenance));node.querySelector('span').textContent=data.maintenance?'Bakım modu: '+(data.globalNotice||'Bazı özellikler geçici olarak kullanılamayabilir.'):data.globalNotice}
function ensureLayer(){let layer=document.getElementById('egAnnouncementLayer');if(layer)return layer;layer=document.createElement('div');layer.id='egAnnouncementLayer';layer.className='eg-announcement-layer';layer.innerHTML='<section class="eg-announcement-sheet"><header class="eg-announcement-head"><h2>Duyurular</h2><button type="button">×</button></header><div id="egAnnouncementList"></div></section>';layer.querySelector('button').onclick=()=>layer.classList.remove('show');layer.onclick=event=>{if(event.target===layer)layer.classList.remove('show')};document.body.appendChild(layer);return layer}
function render(){const list=document.getElementById('egAnnouncementList');if(!list)return;const city=localStorage.getItem('elmaViewerCity')||'Amasya',items=announcements.filter(x=>!x.city||x.city==='Tümü'||x.city===city).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0));list.innerHTML=items.length?items.map(x=>'<article class="eg-public-announcement '+(x.level==='urgent'?'urgent':'')+'"><small>'+String(x.level||'BİLGİ').toLocaleUpperCase('tr-TR')+' · '+String(x.city||'Tümü').toLocaleUpperCase('tr-TR')+'</small><h3></h3><p></p></article>').join(''):'<div class="eg-announcement-empty">Şu anda aktif duyuru yok.</div>';items.forEach((item,index)=>{const card=list.children[index];card.querySelector('h3').textContent=item.title||'Duyuru';card.querySelector('p').textContent=item.body||''})}
window.elmaOpenAnnouncements=()=>{const layer=ensureLayer();render();layer.classList.add('show')};
onSnapshot(doc(db,'adminSettings','public'),snapshot=>notice(snapshot.exists()?snapshot.data():null),()=>{});
onSnapshot(query(collection(db,'announcements'),where('published','==',true),limit(100)),snapshot=>{announcements=snapshot.docs.map(x=>({id:x.id,...x.data()}));render()},()=>{});
})().catch(error=>console.warn('Elma Go yönetim verileri yüklenemedi.',error));
